[project]
name = "gamenn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
main = "main:main"

[tool.uv]
package = true
